### PR TITLE
Improvements to BeamChannel enums

### PR DESCRIPTION
**Pull request by TATDK**
- Fix AudienceRating on BeamChannel
- Fix spelling mistake in CostreamPreference on BeamChannel

### CODE REVIEW

**Comment by MattJustMatt** [comment]
CC: @ttaylorr

**Comment by ttaylorr** [comment]
Looks good! Can you please bump the minor version (from `1.9.2-SNAPSHOT` to `1.10.0-SNAPSHOT`) to indicate that this is a breaking change? Other than that, this is ready to merge :smile:

**Comment by TATDK** [comment]
@ttaylorr Updated as requested ^^

**Comment by ttaylorr** [comment]
Awesome. Thanks again! :+1:

**Pull request merged**
