### PR TITLE
Feature/jwt

### PR DESCRIPTION
**Pull request by JamyDev**

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Looks good, Shame we don't have many tests for this. Something to consider later.

Would like to see expired JWT handling. If not for the app would be good for the client. Should be no reason to do that right this second though it can wait.

**Comment by JamyDev** [comment]
JWT expiring will be added today. One thing I didn't have time to do is add the actual data parsing for each of the events that livesubscribe can register.

**Comment by ProbablePrime** [comment]
this is LGTM

**Comment by ProbablePrime** [comment]
If there's no objections i want to get this in. I'm writing up a constellation tutorial, would be great to add java to the list of clients in that tutorial. @JamyDev ?

**Pull request merged**
