### PR TITLE
Fixed MixerChatConnectable not getting pinged

### PR DESCRIPTION
**Pull request by MJRLegends**

### CODE REVIEW

**Comment by ProbablePrime** [comment]
Odd, i thought the websocket client would be handling pings by default i will have to check.

**Comment by MJRLegends** [comment]
It does not, the consultation websocket has the ping but the chat one didn't and i spent may hours debugging my code just to find out it was this lib not having a ping and as soon as i added the ping code to this lib everything worked for me

**Comment by MJRLegends** [comment]
Seems this kick starts the https://gyazo.com/90575c1aee00d4292eef5410b3ea728c method in JWS lib from org.java_websocket.AbstractWebSocket class

**Comment by MJRLegends** [comment]
Please merge https://github.com/mixer/beam-client-java/pull/77 before this one

**Comment by MJRLegends** [comment]
No longer needed as #77 makes it so websocket lib now supports auto pings

**Pull request closed without merging**
