### PR TITLE
Feat add experience

### PR DESCRIPTION
**Pull request by vijaysharm**
@ttaylorr

### CODE REVIEW

**Comment by ttaylorr** [comment]
Looks good. Could we maybe split this into three atomic commits?
1. Add *.iml to the .gitignore
2. Add experience to BeamUser model
3. Update sparks to be a float

**Comment by vijaysharm** [comment]
@ttaylorr grrr, sorry, turns out that one of my commits arent valid anymore. there was some discussion about whether other not sparks are floats, so i had to drop one of my commits. But i merged the other commits.

**Comment by ttaylorr** [comment]
@vijaysharm hmm, it looks like some of the old commits are still there. Could you preform a [`rebase`](https://git-scm.com/docs/git-rebase) and consolidate them, please?

**Comment by vijaysharm** [comment]
@ttaylorr oops. again, my bad. please look again.

**Comment by ttaylorr** [comment]
Looks like the api.iml changes snuck into the first commit again. I can fix this locally.

**Pull request merged**
